### ISSUE TITLE
Copy on save not working in version 0.1.12

### ISSUE THREAD

**Issue by tallandy** [mightycoco/fsdeploy#16]
Deploy on save appears to be broken in the latest version 0.1.12 on OSX e.g.

`{
    "include":"**/*.*",
    "source":"/Users/andy/workspace/web/project",
    "target":"/Users/andy/workspace/containers/vagrant-aws/server-data/www/project"
}`

The file never gets copied on save.  I've reverted back to 0.1.10 and it works again.

**Comment by dfrt82** [comment]
Can confirm that the most basic functionality of that tool stops working with latest version also under Windows 10. Revert to 0.1.10 fixes the issue.

**Comment by dabeed** [comment]
Same issue. Reverted to 0.1.10 as noted by the others and all is good.

**Comment by rholland** [comment]
same issue on Windows 10. also reverted.

**Comment by mightycoco** [comment]
there was a compatibility issue of minimatch used for single file deploy and the fs-glob patterns used in recursive workspace deploy. fixed in 0.1.13

please let me know, if this fixes the issue. I could only verify against a small set of glob patterns used in the include/exclude settings and this might need a deeper look.

**Comment by tallandy** [comment]
@mightycoco just tried 0.1.13 and copy on save seems to be working fine again

**Comment by mightycoco** [comment]
fixed in 86045ad95a85d01e99c4703db153a05c9e231131
